//go:build darwin
// +build darwin

package cranelift

import (
	"fmt"
	"os"

	"github.com/omni-lang/omni/internal/mir"
)

// CompileMIRJSON delegates MIR emission to the native Cranelift bridge.
func CompileMIRJSON(json string) error {
	return fmt.Errorf("cranelift backend not available on macOS")
}

// CompileToObject compiles MIR to a native object file.
func CompileToObject(json string, outputPath string) error {
	return fmt.Errorf("cranelift backend not available on macOS")
}

// CompileModuleToObject compiles a MIR module to a native object file.
func CompileModuleToObject(module *mir.Module, outputPath string) error {
	// For now, create a placeholder object file on macOS
	placeholder := []byte("# OmniLang Object File Placeholder (macOS)\n# This would contain native machine code generated by Cranelift\n")

	if err := os.WriteFile(outputPath, placeholder, 0o644); err != nil {
		return fmt.Errorf("write object output: %w", err)
	}

	return nil
}
